/**
 * validate-carousel.ts
 *
 * Validates carousel slide content before it is passed to the Puppeteer
 * renderer and Buffer handoff.  Call this after AI generation and before
 * renderCarousel() so bad data is caught early with a clear message rather
 * than producing blank or broken slides.
 *
 * Usage:
 *   const result = validateCarousel(slideContent)
 *   if (!result.valid) throw new Error(result.errors.join("; "))
 */

export interface CarouselSlide {
  headline:  string
  body?:     string
  isCTA?:    boolean
  isHook?:   boolean
  mediaUrl?: string | null
}

export interface CarouselValidationResult {
  valid:    boolean
  errors:   string[]
  warnings: string[]
}

/** Maximum slides Instagram supports in a single post */
const INSTAGRAM_MAX_SLIDES = 10

/** Character limits that match the truncation inside the templates */
const LIMITS = {
  hookHeadline:    150,
  contentHeadline: 120,  // text-only layout
  contentHeadlineMedia: 110,  // image layout (less vertical space for text)
  contentBody:     300,
  contentBodyMedia: 220,
  ctaHeadline:     100,
  ctaBody:         160,
}

/**
 * Validate an array of carousel slide-content items.
 *
 * @param slides         - The content slides array (hook + content + cta, as
 *                         generated by the AI).  Do NOT pre-filter; pass the
 *                         full array so total count can be checked.
 * @param templateSlug   - Optional: "carousel-edu" or "carousel-myth".
 *                         Used to calculate the real rendered slide count.
 */
export function validateCarousel(
  slides:       CarouselSlide[],
  templateSlug?: string,
): CarouselValidationResult {
  const errors:   string[] = []
  const warnings: string[] = []

  // ── 1. Slide count ────────────────────────────────────────────
  if (slides.length === 0) {
    errors.push("Carousel has no slides.")
    return { valid: false, errors, warnings }
  }

  // Calculate the number of rendered slides (templates add hook + CTA)
  const renderedCount = templateSlug === "carousel-myth"
    ? 1 + (slides.length * 2) + 1     // 1 hook + myth+reality pairs + 1 CTA
    : slides.length + 2               // 1 hook + N content + 1 CTA (edu default)

  if (renderedCount > INSTAGRAM_MAX_SLIDES) {
    warnings.push(
      `This carousel will render ${renderedCount} slides — Instagram supports a maximum of ${INSTAGRAM_MAX_SLIDES}. ` +
      `Reduce content slides to ${templateSlug === "carousel-myth" ? Math.floor((INSTAGRAM_MAX_SLIDES - 2) / 2) : INSTAGRAM_MAX_SLIDES - 2} or fewer.`
    )
  }

  if (slides.length < 1) {
    errors.push("At least 1 content slide is required.")
  }

  // ── 2. Per-slide validation ───────────────────────────────────
  slides.forEach((slide, i) => {
    const num = i + 1

    if (!slide.headline?.trim()) {
      errors.push(`Slide ${num}: headline is required.`)
      return
    }

    const hasMedia     = Boolean(slide.mediaUrl)
    const headlineMax  = hasMedia ? LIMITS.contentHeadlineMedia : LIMITS.contentHeadline
    const bodyMax      = hasMedia ? LIMITS.contentBodyMedia     : LIMITS.contentBody

    if (slide.headline.length > headlineMax) {
      warnings.push(
        `Slide ${num}: headline is ${slide.headline.length} chars — will be truncated to ${headlineMax}.`
      )
    }

    if (slide.body && slide.body.length > bodyMax) {
      warnings.push(
        `Slide ${num}: body text is ${slide.body.length} chars — will be truncated to ${bodyMax}.`
      )
    }
  })

  return { valid: errors.length === 0, errors, warnings }
}

/**
 * Convenience: throws if the carousel is invalid, logs warnings.
 * Use in API routes where you want a hard stop on bad data.
 */
export function assertCarouselValid(
  slides:       CarouselSlide[],
  templateSlug?: string,
): void {
  const result = validateCarousel(slides, templateSlug)

  if (result.warnings.length) {
    console.warn("[validate-carousel] warnings:", result.warnings)
  }

  if (!result.valid) {
    throw new Error(
      `Carousel validation failed: ${result.errors.join("; ")}`
    )
  }
}
